server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka/
    
spring:
  application:
    name: jinfo
  data:
    mongodb:
    host: mongo-0
    port: 27017
