version: "3"
services:
  eurekaservice:
    image: awsazuser/scesrv:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    hostname: eurekaservice
    ports:
    - "8761:8761"
    networks:
      - springnw
  product:
    image: awsazuser/scecli1:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "8091:8091"
    networks:
      - springnw
  jinfo:
    image: awsazuser/scecli3:latest
    deploy:
      replicas: 2
      placement:
        constraints: [node.role != manager]
    networks:
      - springnw
  osinfo:
    image: awsazuser/scecli2:latest
    deploy:
      replicas: 3
      placement:
        constraints: [node.role != manager]
    networks:
      - springnw
  zuul:
    image: awsazuser/sczuul:latest
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - springnw
  mongo-0:
    image: mongo:latest
    hostname: mongo-0
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "27017:27017"
    networks:
       - springnw

networks:
  springnw:
