server:
   port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka/

zuul:
  Eureka:
  prefix: /api
  routes:
    osinfo:
      path: /osinfo/**
      serviceId: OSINFO
    jinfo:
      path: /jinfo/**
      serviceId: JINFO
    rbnclient:
      path: /jversion/**
      serviceId: JVERSION

spring:
  application:
    name: zuul

management:
  security:
    enabled: false