server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
spring:
  application:
    name: jinfo
