apiVersion: v1
kind: Service
metadata:
  name: jinfo
  labels:
    name: jinfo
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    role: jinfo

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jinfo
spec:
  selector:
    matchLabels:
      app: jinfo
  replicas: 5
  template:
    metadata:
      labels:
        app: jinfo
    spec:
      containers:
      - name: eurekaservice
        image: awsazuser/eurekaclient3:latest
        ports:
        - containerPort: 8090
