apiVersion: v1
kind: Service
metadata:
  name: mongo-0
  labels:
    name: mongo-0
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongo
---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
